spring:
  application:
    name: rolling-bites
  profiles:
    group:
      "local": "local, common"
      "dev": "devdb, common"
      "prod": "proddb, common"
    active: local



---

springdoc:
  swagger-ui:
    path: /api-docs

    groups-order: DESC

    tags-sorter: alpha

    operations-sorter: method
  cache:
    disabled: true
